# Generated by Django 5.2 on 2025-04-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название канала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='channel_logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Телеканал',
                'verbose_name_plural': 'Телеканалы',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_date', models.DateField(verbose_name='Дата выхода в эфир')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок выпуска')),
            ],
            options={
                'verbose_name': 'Выпуск',
                'verbose_name_plural': 'Выпуски',
                'ordering': ['-air_date'],
            },
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL видео'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('auto', 'Автоопределение')], default='auto', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='AnalysisMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_appeal', models.FloatField(default=50.0, verbose_name='Интерес для мужчин (%)')),
                ('female_appeal', models.FloatField(default=50.0, verbose_name='Интерес для женщин (%)')),
                ('children_friendly', models.BooleanField(default=False, verbose_name='Подходит для детей')),
                ('age_0_12', models.FloatField(default=0.0, verbose_name='Интерес для возраста 0-12 (%)')),
                ('age_13_17', models.FloatField(default=0.0, verbose_name='Интерес для возраста 13-17 (%)')),
                ('age_18_35', models.FloatField(default=0.0, verbose_name='Интерес для возраста 18-35 (%)')),
                ('age_36_55', models.FloatField(default=0.0, verbose_name='Интерес для возраста 36-55 (%)')),
                ('age_56_plus', models.FloatField(default=0.0, verbose_name='Интерес для возраста 56+ (%)')),
                ('educational_value', models.FloatField(default=0.0, verbose_name='Образовательная ценность (0-100)')),
                ('entertainment_value', models.FloatField(default=0.0, verbose_name='Развлекательная ценность (0-100)')),
                ('information_quality', models.FloatField(default=0.0, verbose_name='Качество информации (0-100)')),
                ('positive_tone', models.FloatField(default=0.0, verbose_name='Позитивный тон (%)')),
                ('neutral_tone', models.FloatField(default=0.0, verbose_name='Нейтральный тон (%)')),
                ('negative_tone', models.FloatField(default=0.0, verbose_name='Негативный тон (%)')),
                ('topics', models.JSONField(default=list, verbose_name='Ключевые темы')),
                ('media_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.mediafile', verbose_name='Медиафайл')),
            ],
            options={
                'verbose_name': 'Метрики анализа',
                'verbose_name_plural': 'Метрики анализа',
            },
        ),
        migrations.AddField(
            model_name='mediafile',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='core.episode', verbose_name='Выпуск'),
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название передачи')),
                ('category', models.CharField(choices=[('news', 'Новости'), ('entertainment', 'Развлекательная'), ('educational', 'Познавательная'), ('children', 'Детская'), ('sport', 'Спортивная'), ('political', 'Политическая'), ('cultural', 'Культурная'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='core.channel', verbose_name='Телеканал')),
            ],
            options={
                'verbose_name': 'Телепередача',
                'verbose_name_plural': 'Телепередачи',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.tvshow', verbose_name='Телепередача'),
        ),
    ]
