# Generated by Django 5.2 on 2025-04-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL видео'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kk', 'Казахский'), ('auto', 'Автоопределение')], default='auto', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
